export const WORLD_CUP_TEAM_COSTS = [
  ["Spain", 24],
  ["France", 23],
  ["Argentina", 22],
  ["Brazil", 20],
  ["England", 21],
  ["Germany", 21],
  ["Netherlands", 20],
  ["Portugal", 20],
  ["Mexico", 18],
  ["Colombia", 17],
  ["Croatia", 17],
  ["Norway", 17],
  ["Belgium", 16],
  ["Canada", 16],
  ["Ecuador", 16],
  ["Switzerland", 16],
  ["Turkiye", 16],
  ["Japan", 15],
  ["Senegal", 15],
  ["Uruguay", 15],
  ["USA", 15],
  ["Austria", 14],
  ["Czechia", 14],
  ["IR Iran", 14],
  ["Korea Republic", 14],
  ["Morocco", 14],
  ["Paraguay", 14],
  ["Australia", 13],
  ["Bosnia and Herzegovina", 13],
  ["Egypt", 13],
  ["Scotland", 13],
  ["Algeria", 12],
  ["Cote d'Ivoire", 12],
  ["Jordan", 12],
  ["New Zealand", 12],
  ["Panama", 12],
  ["Sweden", 12],
  ["Uzbekistan", 12],
  ["Cabo Verde", 10],
  ["Tunisia", 10],
  ["Congo DR", 9],
  ["Saudi Arabia", 9],
  ["South Africa", 9],
  ["Curacao", 8],
  ["Haiti", 8],
  ["Ghana", 7],
  ["Qatar", 7],
  ["Iraq", 4],
] as const;

export const WORLD_CUP_SCORING_EVENTS = [
  ["Group-stage win", 6],
  ["Group-stage draw", 2],
  ["Advance from group to Round of 32", 12],
  ["Win Round of 32 and reach Round of 16", 18],
  ["Win Round of 16 and reach quarterfinal", 30],
  ["Win quarterfinal and reach semifinal", 48],
  ["Win semifinal and reach final", 72],
  ["Win final and become champion", 100],
] as const;

export const WORLD_CUP_VALUE_BONUS_EVENTS = [
  ["Group-stage win", "+4"],
  ["Advance from group", "+10"],
  ["Reach Round of 16", "+8"],
  ["Reach quarterfinal", "+16"],
  ["Reach semifinal", "+28"],
  ["Reach final", "+42"],
  ["Become champion", "+60"],
] as const;
