export const WORLD_CUP_TEAM_COSTS = [
  ["Spain", 24],
  ["France", 21],
  ["Argentina", 19],
  ["Brazil", 16],
  ["England", 14],
  ["Netherlands", 14],
  ["Germany", 13],
  ["Portugal", 13],
  ["Colombia", 11],
  ["Mexico", 11],
  ["Belgium", 10],
  ["Croatia", 10],
  ["Norway", 10],
  ["Switzerland", 10],
  ["Canada", 9],
  ["Ecuador", 9],
  ["Turkiye", 9],
  ["Japan", 8],
  ["Morocco", 8],
  ["Paraguay", 8],
  ["Senegal", 8],
  ["Uruguay", 8],
  ["USA", 8],
  ["Australia", 7],
  ["Austria", 7],
  ["Czechia", 7],
  ["IR Iran", 7],
  ["Korea Republic", 7],
  ["Algeria", 6],
  ["Bosnia and Herzegovina", 6],
  ["Cote d'Ivoire", 6],
  ["Egypt", 6],
  ["Jordan", 6],
  ["New Zealand", 6],
  ["Panama", 6],
  ["Scotland", 6],
  ["Sweden", 6],
  ["Uzbekistan", 6],
  ["Cabo Verde", 5],
  ["Congo DR", 5],
  ["Tunisia", 5],
  ["Curacao", 4],
  ["Ghana", 4],
  ["Haiti", 4],
  ["Iraq", 4],
  ["Qatar", 4],
  ["Saudi Arabia", 4],
  ["South Africa", 4],
] as const;

export const WORLD_CUP_SCORING_EVENTS = [
  ["Group-stage win", 6],
  ["Group-stage draw", 2],
  ["Advance from group to Round of 32", 12],
  ["Win Round of 32 and reach Round of 16", 18],
  ["Win Round of 16 and reach quarterfinal", 30],
  ["Win quarterfinal and reach semifinal", 48],
  ["Win semifinal and reach final", 72],
  ["Win final and become champion", 100],
] as const;

export const WORLD_CUP_VALUE_BONUS_EVENTS = [
  ["Advance from group", "1 x value unit"],
  ["Reach Round of 16", "2 x value unit"],
  ["Reach quarterfinal", "4 x value unit"],
  ["Reach semifinal", "6 x value unit"],
  ["Reach final", "8 x value unit"],
  ["Become champion", "12 x value unit"],
] as const;
